# Generated by Django 4.2.6 on 2023-10-16 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='default@email.com', max_length=254)),
                ('pdf_file', models.FileField(upload_to='resumes/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.department')),
                ('iin', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes_as_iin', to='integration.employee')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes_as_name', to='integration.employee')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.position')),
            ],
        ),
    ]
