# Generated by Django 4.2.6 on 2023-10-15 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_alter_approvalrequest_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalrequest',
            name='user_id',
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='iin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.employee'),
        ),
    ]
