# Generated by Django 4.2.6 on 2023-10-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0007_alter_approvalrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='iin',
            field=models.IntegerField(blank=True, max_length=12),
        ),
    ]
