# Generated by Django 4.2.6 on 2023-10-15 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0008_alter_employee_iin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalrequest',
            old_name='iin',
            new_name='itin',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='iin',
            new_name='itin',
        ),
    ]
