# Generated by Django 4.2.6 on 2023-10-16 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integration', '0009_rename_iin_approvalrequest_itin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expertcommission',
            name='members',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_commissions', to='integration.employee'),
        ),
    ]
